version: "3.9"
services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
  web:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
